name: test-build-linux
on: [push]
jobs:
  test-build-linux:
    runs-on: ubuntu-18.04
    env: 
      BUILD_PATH: ${{env.GITHUB_WORKSPACE}}/build
      INSTALL_PATH: ${{BUILD_PATH}}/Install
    steps:
      - uses: actions/checkout@v2
        with:
          # path: supercollider # FIXME: replace with env var
          submodules: recursive

      - name: install-dependencies
        run: sudo apt-get update && sudo apt-get install --yes build-essential cmake pkg-config libjack-jackd2-dev libsndfile1-dev libasound2-dev libavahi-client-dev libreadline6-dev libfftw3-dev libicu-dev libxt-dev libudev-dev
      - name: install-qt
        run: sudo apt-get install qt5-default qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev qtwebengine5-dev libqt5svg5-dev libqt5websockets5-dev
      - name: make-build-dir
        run: mkdir $BUILD_PATH # export VERSION_TO_BUILD=${TRAVIS_TAG##Version-}
      - name: cd
        run: cd $GITHUB_WORKSPACE/build # does not persist between actions
      - name: where-am-i
        run: pwd
      - name: where-is-gh
        run: echo $GITHUB_WORKSPACE
      - name: cmake
        run: cd $BUILD_PATH && cmake -DSC_EL=OFF -DSC_VIM=OFF -DSC_ED=OFF -DSC_QT=ON -DSC_IDE=ON  -DCMAKE_INSTALL_PREFIX:PATH=$BUILD_PATH -DCMAKE_BUILD_TYPE=Release .. --debug-output # -DCMAKE_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/BUILD/Install
      - name: build
        run: cd $BUILD_PATH && make install -j2
