name: test-CI
on: [push]
jobs:
  test-build-linux:
    runs-on: ubuntu-18.04
    env: 
      # BUILD_PATH: ${{env.GITHUB_WORKSPACE}}/build
      # INSTALL_PATH: ${{BUILD_PATH}}/Install
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install-dependencies
        run: sudo apt-get update && sudo apt-get install --yes build-essential cmake pkg-config libjack-jackd2-dev libsndfile1-dev libasound2-dev libavahi-client-dev libreadline6-dev libfftw3-dev libicu-dev libxt-dev libudev-dev # I was getting errors when apt-get update was not run first
      - name: install-qt
        run: sudo apt-get install qt5-default qt5-qmake qttools5-dev qttools5-dev-tools qtdeclarative5-dev qtwebengine5-dev libqt5svg5-dev libqt5websockets5-dev
      - name: make-build-dir
        run: mkdir $GITHUB_WORKSPACE/build # export VERSION_TO_BUILD=${TRAVIS_TAG##Version-}
      - name: cd
        run: cd $GITHUB_WORKSPACE/build # does not persist between actions
      - name: where-am-i
        run: pwd
      - name: where-is-gh
        run: echo $GITHUB_WORKSPACE
      - name: configure
        run: cd $GITHUB_WORKSPACE/build && cmake -DSC_EL=OFF -DSC_VIM=OFF -DSC_ED=OFF -DSC_QT=ON -DSC_IDE=ON  -DCMAKE_INSTALL_PREFIX:PATH=$GITHUB_WORKSPACE/build/Install -DCMAKE_BUILD_TYPE=Release .. --debug-output # -DCMAKE_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/BUILD/Install
      - name: build
        run: cd $GITHUB_WORKSPACE/build && make install -j2
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sc-${{ github.workflow }}-#{{ github.sha }}
          path: ${{ github.workspace }}/build/Install/*

  test-build-macos:
    runs-on: macos-10.15
    env: 
      BUILD_PATH: ${{ github.workshpace }}/build
      INSTALL_PATH: ${{ emv.build_path }}/Install
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_NO_INSTALL_CLEANUP: 1
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install-dependencies
        run: brew install libsndfile portaudio ccache qt fftw
      # - name: install-qt
        # run: brew install qt
      - name: make-build-dir
        run: mkdir $GITHUB_WORKSPACE/build # export VERSION_TO_BUILD=${TRAVIS_TAG##Version-}
      # - name: cd
        # run: cd $GITHUB_WORKSPACE/build # does not persist between actions
      # - name: where-am-i
        # run: pwd # /home/runner/work/supercollider/supercollider
      # - name: where-is-gh
        # run: echo $GITHUB_WORKSPACE # /home/runner/work/supercollider/supercollider
      - name: configure
        run: |
        cd $GITHUB_WORKSPACE/build && \
        cmake -G "Xcode" \
            # -DRULE_LAUNCH_COMPILE=ccache \
            -DCMAKE_PREFIX_PATH=`brew --prefix qt5` \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 \
            -DSUPERNOVA=ON \
            # $EXTRA_CMAKE_FLAGS \
            -DCMAKE_BUILD_TYPE=Release .. --debug-output
      - name: build
        run: cmake --build $GITHUB_WORKSPACE/build --config Release --target install
      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sc-${{ github.workflow }}-#{{ github.sha }}
          path: ${{ github.workspace }}/build/Install/*
